-- PBM v1 project-centric ERP: quotes, procurement and finance core

CREATE TABLE IF NOT EXISTS project_quote (
    project_quote_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT UNSIGNED NOT NULL,
    quote_reference VARCHAR(100) NOT NULL,
    quote_type_code VARCHAR(100) NOT NULL DEFAULT 'fee_proposal',
    quote_status_code VARCHAR(100) NOT NULL DEFAULT 'draft',
    issue_date DATE NULL,
    expiry_date DATE NULL,
    accepted_date DATE NULL,
    rejected_date DATE NULL,
    subtotal_amount DECIMAL(18,2) NULL,
    tax_amount DECIMAL(18,2) NULL,
    total_amount DECIMAL(18,2) NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'GBP',
    assumptions TEXT NULL,
    exclusions TEXT NULL,
    terms TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_project_quote_project FOREIGN KEY (project_id) REFERENCES project (project_id),
    UNIQUE KEY uq_project_quote_reference (quote_reference),
    INDEX ix_project_quote_project (project_id),
    INDEX ix_project_quote_status (quote_status_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_quote_row (
    project_quote_row_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    project_quote_id BIGINT UNSIGNED NOT NULL,
    project_service_id BIGINT UNSIGNED NULL,
    line_number INT NOT NULL DEFAULT 1,
    description TEXT NOT NULL,
    quantity DECIMAL(18,4) NULL,
    unit_code VARCHAR(50) NULL,
    unit_cost DECIMAL(18,4) NULL,
    unit_price DECIMAL(18,4) NULL,
    margin_percent DECIMAL(9,4) NULL,
    line_total DECIMAL(18,2) NULL,
    tax_code VARCHAR(50) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_project_quote_row_quote FOREIGN KEY (project_quote_id) REFERENCES project_quote (project_quote_id),
    CONSTRAINT fk_project_quote_row_service FOREIGN KEY (project_service_id) REFERENCES project_service (project_service_id),
    UNIQUE KEY uq_project_quote_row_line (project_quote_id, line_number),
    INDEX ix_project_quote_row_quote (project_quote_id),
    INDEX ix_project_quote_row_service (project_service_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS purchase_order (
    purchase_order_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT UNSIGNED NULL,
    supplier_business_partner_id BIGINT UNSIGNED NOT NULL,
    purchase_order_reference VARCHAR(100) NOT NULL,
    purchase_order_status_code VARCHAR(100) NOT NULL DEFAULT 'draft',
    issue_date DATE NULL,
    expected_delivery_date DATE NULL,
    subtotal_amount DECIMAL(18,2) NULL,
    tax_amount DECIMAL(18,2) NULL,
    total_amount DECIMAL(18,2) NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'GBP',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_purchase_order_project FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT fk_purchase_order_supplier FOREIGN KEY (supplier_business_partner_id) REFERENCES business_partner (business_partner_id),
    UNIQUE KEY uq_purchase_order_reference (purchase_order_reference),
    INDEX ix_purchase_order_project (project_id),
    INDEX ix_purchase_order_supplier (supplier_business_partner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS purchase_order_row (
    purchase_order_row_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    purchase_order_id BIGINT UNSIGNED NOT NULL,
    project_service_id BIGINT UNSIGNED NULL,
    line_number INT NOT NULL DEFAULT 1,
    description TEXT NOT NULL,
    quantity DECIMAL(18,4) NULL,
    unit_code VARCHAR(50) NULL,
    unit_price DECIMAL(18,4) NULL,
    line_total DECIMAL(18,2) NULL,
    tax_code VARCHAR(50) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_purchase_order_row_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_order (purchase_order_id),
    CONSTRAINT fk_purchase_order_row_service FOREIGN KEY (project_service_id) REFERENCES project_service (project_service_id),
    UNIQUE KEY uq_purchase_order_row_line (purchase_order_id, line_number),
    INDEX ix_purchase_order_row_order (purchase_order_id),
    INDEX ix_purchase_order_row_service (project_service_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_invoice (
    supplier_invoice_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT UNSIGNED NULL,
    supplier_business_partner_id BIGINT UNSIGNED NOT NULL,
    purchase_order_id BIGINT UNSIGNED NULL,
    supplier_invoice_reference VARCHAR(100) NOT NULL,
    invoice_status_code VARCHAR(100) NOT NULL DEFAULT 'received',
    invoice_date DATE NULL,
    due_date DATE NULL,
    subtotal_amount DECIMAL(18,2) NULL,
    tax_amount DECIMAL(18,2) NULL,
    total_amount DECIMAL(18,2) NULL,
    amount_paid DECIMAL(18,2) NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'GBP',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_supplier_invoice_project FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT fk_supplier_invoice_supplier FOREIGN KEY (supplier_business_partner_id) REFERENCES business_partner (business_partner_id),
    CONSTRAINT fk_supplier_invoice_purchase_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_order (purchase_order_id),
    INDEX ix_supplier_invoice_project (project_id),
    INDEX ix_supplier_invoice_supplier (supplier_business_partner_id),
    INDEX ix_supplier_invoice_po (purchase_order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_invoice_row (
    supplier_invoice_row_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    supplier_invoice_id BIGINT UNSIGNED NOT NULL,
    purchase_order_row_id BIGINT UNSIGNED NULL,
    project_service_id BIGINT UNSIGNED NULL,
    line_number INT NOT NULL DEFAULT 1,
    description TEXT NOT NULL,
    quantity DECIMAL(18,4) NULL,
    unit_code VARCHAR(50) NULL,
    unit_cost DECIMAL(18,4) NULL,
    line_total DECIMAL(18,2) NULL,
    tax_code VARCHAR(50) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_supplier_invoice_row_invoice FOREIGN KEY (supplier_invoice_id) REFERENCES supplier_invoice (supplier_invoice_id),
    CONSTRAINT fk_supplier_invoice_row_po_row FOREIGN KEY (purchase_order_row_id) REFERENCES purchase_order_row (purchase_order_row_id),
    CONSTRAINT fk_supplier_invoice_row_service FOREIGN KEY (project_service_id) REFERENCES project_service (project_service_id),
    UNIQUE KEY uq_supplier_invoice_row_line (supplier_invoice_id, line_number),
    INDEX ix_supplier_invoice_row_invoice (supplier_invoice_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sales_invoice (
    sales_invoice_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT UNSIGNED NULL,
    client_business_partner_id BIGINT UNSIGNED NOT NULL,
    invoice_reference VARCHAR(100) NOT NULL,
    invoice_status_code VARCHAR(100) NOT NULL DEFAULT 'draft',
    invoice_date DATE NULL,
    due_date DATE NULL,
    subtotal_amount DECIMAL(18,2) NULL,
    tax_amount DECIMAL(18,2) NULL,
    total_amount DECIMAL(18,2) NULL,
    amount_paid DECIMAL(18,2) NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'GBP',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_sales_invoice_project FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT fk_sales_invoice_client FOREIGN KEY (client_business_partner_id) REFERENCES business_partner (business_partner_id),
    UNIQUE KEY uq_sales_invoice_reference (invoice_reference),
    INDEX ix_sales_invoice_project (project_id),
    INDEX ix_sales_invoice_client (client_business_partner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sales_invoice_row (
    sales_invoice_row_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sales_invoice_id BIGINT UNSIGNED NOT NULL,
    project_quote_row_id BIGINT UNSIGNED NULL,
    project_service_id BIGINT UNSIGNED NULL,
    line_number INT NOT NULL DEFAULT 1,
    description TEXT NOT NULL,
    quantity DECIMAL(18,4) NULL,
    unit_code VARCHAR(50) NULL,
    unit_price DECIMAL(18,4) NULL,
    line_total DECIMAL(18,2) NULL,
    tax_code VARCHAR(50) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_sales_invoice_row_invoice FOREIGN KEY (sales_invoice_id) REFERENCES sales_invoice (sales_invoice_id),
    CONSTRAINT fk_sales_invoice_row_quote_row FOREIGN KEY (project_quote_row_id) REFERENCES project_quote_row (project_quote_row_id),
    CONSTRAINT fk_sales_invoice_row_service FOREIGN KEY (project_service_id) REFERENCES project_service (project_service_id),
    UNIQUE KEY uq_sales_invoice_row_line (sales_invoice_id, line_number),
    INDEX ix_sales_invoice_row_invoice (sales_invoice_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
